"""add resume columns to sync_logs

Revision ID: 5c258eaf4e4c
Revises: d20bcdc0a20e
Create Date: 2026-03-01 14:33:32.599788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c258eaf4e4c'
down_revision = 'd20bcdc0a20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_endpoint', sa.String(length=50), nullable=True, comment='endpoint terakhir yang diproses'))
        batch_op.add_column(sa.Column('last_synced_page', sa.Integer(), nullable=True, comment='page terakhir yang berhasil diproses'))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True, comment='pesan error jika gagal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('last_synced_page')
        batch_op.drop_column('last_synced_endpoint')

    # ### end Alembic commands ###
