"""add column deleted_at

Revision ID: 60051043a7b0
Revises: 5c258eaf4e4c
Create Date: 2026-03-07 12:33:10.259430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60051043a7b0'
down_revision = '5c258eaf4e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               comment='tmdb, user, admin',
               existing_comment='tmdb, user',
               existing_nullable=False)

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('last_synced_endpoint',
               existing_type=sa.VARCHAR(length=50),
               comment='last endpoint synced',
               existing_comment='endpoint terakhir yang diproses',
               existing_nullable=True)
        batch_op.alter_column('last_synced_page',
               existing_type=sa.INTEGER(),
               comment='last page synced',
               existing_comment='page terakhir yang berhasil diproses',
               existing_nullable=True)
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               comment='error message if failed',
               existing_comment='pesan error jika gagal',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.TEXT(),
               comment='pesan error jika gagal',
               existing_comment='error message if failed',
               existing_nullable=True)
        batch_op.alter_column('last_synced_page',
               existing_type=sa.INTEGER(),
               comment='page terakhir yang berhasil diproses',
               existing_comment='last page synced',
               existing_nullable=True)
        batch_op.alter_column('last_synced_endpoint',
               existing_type=sa.VARCHAR(length=50),
               comment='endpoint terakhir yang diproses',
               existing_comment='last endpoint synced',
               existing_nullable=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               comment='tmdb, user',
               existing_comment='tmdb, user, admin',
               existing_nullable=False)

    # ### end Alembic commands ###
